[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.20"
evm_version = "paris"

remappings = [
    "@chainlink/contracts-ccip/=lib/ccip/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[etherscan]
fuji = { key = "${FUJI_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
